flask_app/views.py
import os
from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify, current_app
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.utils import secure_filename
from flask_app import db, auth
from flask_app.forms import SignUpForm, LoginForm, CreateGenreForm, CreateSiteForm, PostCommentForm
from flask_app.models import User, Genre, Sitedata, Comment, Picture

main = Blueprint(
    "main",
    __name__,
    template_folder="templates",
    static_folder="static",
)

# メインの地図のページ
@main.route("/")
@login_required
@auth.login_required
def maps():
    genres = Genre.query.all()
    Users = User.query.all()
    return render_template("maps.html", genres=genres)

@main.route("/data")
@auth.login_required
def get_data():
    sites = Sitedata.query.all()
    data = []
    for site in sites:
        category_id = site.category
        data.append({
            "siteid": site.siteid,
            "sitename": site.sitename,
            "coordinates": site.coordinates,
            "categoryid": category_id,
            "categoryname": Genre.query.filter_by(genid=category_id).one().genname,
        })
    json_data = jsonify(data)
    return json_data

@main.route("/data/<int:site_id>")
@auth.login_required
def get_sitedata(site_id):
    site = Sitedata.query.filter_by(siteid=site_id).first()
    category_id = site.category
    data = [{
        "siteid": site.siteid,
        "sitename": site.sitename,
        "coordinates": site.coordinates,
        "categoryid": category_id,
        "categoryname": Genre.query.filter_by(genid=category_id).one().genname,
    }]
    json_data = jsonify(data)
    return json_data

@main.route("/genres_data")
@auth.login_required
def get_genre_data():
    genres = Genre.query.all()
    data = []
    for genre in genres:
        data.append({
            "genid": genre.genid,
            "genname": genre.genname,
        })
    json_data = jsonify(data)
    return json_data

# サインアップページ
@main.route("/signup", methods=["GET", "POST"])
@auth.login_required
def signup():
    form = SignUpForm()
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )

        if user.is_duplicate_email():
            flash("指定のメールアドレスは登録済みです")
            return redirect(url_for("main.signup"))

        db.session.add(user)
        db.session.commit()

        login_user(user)

        next_ = request.args.get("next")
        if next_ is None or not next_.startswith("/"):
            next_ = url_for("main.maps")
        return redirect(next_)

    return render_template("signup.html", form=form)

# ログインページ
@main.route("/login", methods=["GET", "POST"])
@auth.login_required
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.query(User).filter_by(email=form.email.data).first()

        if user is not None and user.verify_password(form.password.data):
            login_user(user)
            return redirect(url_for("main.maps"))
        
        flash("メールアドレスかパスワードが不正です")
    return render_template("login.html", form=form)

# ログアウトする時に用いる
@main.route("/logout")
@auth.login_required
def logout():
    logout_user()
    return redirect(url_for("main.login"))

# ユーザ一覧 開発用
@main.route("/users")
@login_required
@auth.login_required
def users():
    users = db.session.query(User).all()
    return render_template("users.html", users=users)

# ユーザ情報編集
@main.route("/users/<int:user_id>", methods=["GET", "POST"])
@login_required
@auth.login_required
def edit_user(user_id):
    form = SignUpForm()
    user = User.query.filter_by(id=user_id).first()
    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.commit()
        return redirect(url_for("main.users"))
    return render_template("edit_user.html", user=user, form=form)

# ユーザ削除
@main.route("/users/<int:user_id>/delete", methods=["POST"])
@login_required
@auth.login_required
def delete_user(user_id):
    user = db.session.query(User).filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("main.users"))

# ジャンル一覧 開発用？
@main.route("/genres")
@login_required
@auth.login_required
def genres():
    genres = db.session.query(Genre).all()
    return render_template("genre/genres.html", genres=genres)

# ジャンル作成ページ
@main.route("/create_genre", methods=["GET", "POST"])
@login_required
@auth.login_required
def create_genre():
    form = CreateGenreForm()
    if form.validate_on_submit():
        genre = Genre(
            genname=form.genname.data,
            caption=form.caption.data,
            pins=0,
            creator=current_user.get_id()
        )
        db.session.add(genre)
        db.session.commit()

        return redirect(url_for("main.genres"))

    return render_template("genre/create_genre.html", form=form)

# ジャンル情報
@main.route("/genre/<int:genre_id>", methods=["GET"])
@login_required
@auth.login_required
def genre_info(genre_id):
    genre = Genre.query.filter_by(genid=genre_id).first()
    sites = Sitedata.query.filter_by(category=genre_id).all()
    creator = User.query.filter_by(id=genre.creator).first()
    return render_template("genre/genre_info.html", genre=genre, sites=sites, creator=creator)

# ジャンル情報（開発用）
@main.route("/genre/dev", methods=["GET"])
@auth.login_required
def dev_genre_info():
    return render_template("genre/dev_genre_info.html")

# ジャンル情報編集
@main.route("/edit_genre/<int:genre_id>", methods=["GET", "POST"])
@login_required
@auth.login_required
def edit_genre(genre_id):
    form = CreateGenreForm()
    genre = Genre.query.filter_by(genid=genre_id).first()
    current = int(current_user.get_id())
    if form.validate_on_submit():
        genre.genname = form.genname.data
        db.session.commit()
        return redirect(url_for("main.genres"))
    return render_template("genre/edit_genre.html", genre=genre, form=form, current=current)

# ジャンル削除
@main.route("/genre/<int:genre_id>/delete", methods=["POST"])
@login_required
@auth.login_required
def delete_genre(genre_id):
    genre = db.session.query(Genre).filter_by(genid=genre_id).first()
    sites = db.session.query(Sitedata).filter_by(category=genre_id).all()
    db.session.delete(genre)
    for site in sites:
        db.session.delete(site)
    db.session.commit()
    return redirect(url_for("main.genres"))

# サイト作成ページ
@main.route("/create_site/<int:genre_id>", methods=["GET", "POST"])
@login_required
@auth.login_required
def create_site(genre_id):
    genre = db.session.query(Genre).filter_by(genid=genre_id).first()
    form = CreateSiteForm()
    if form.validate_on_submit():

        site = Sitedata(
            sitename=form.sitename.data,
            category=genre_id,
            content=form.content.data,
            coordinates=str(form.latitude.data) + "," + str(form.longitude.data),
            creator=current_user.get_id()
        )
        db.session.add(site)
        db.session.flush()

        if form.image.data:
            image = form.image.data
            extension = os.path.splitext(image.filename)[1]
            filename = f"site{site.siteid}{extension}"
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            os.makedirs(os.path.dirname(image_path), exist_ok=True)
            image.save(image_path)
            picture = Picture(
                poster = current_user.id,
                siteid = site.siteid,
                path = filename,
            )
            db.session.add(picture)

        genre.pins += 1
        db.session.commit()

        return redirect(url_for("main.genre_info", genre_id=genre.genid))

    return render_template("site/create_site.html", genre=genre, form=form)

# サイト情報
@main.route("/site/<int:site_id>", methods=["GET"])
@login_required
@auth.login_required
def site_info(site_id):
    site = Sitedata.query.filter_by(siteid=site_id).first()
    genre = Genre.query.filter_by(genid=site.category).first()
    creator = User.query.filter_by(id=genre.creator).first()
    comments = Comment.query.filter_by(siteid=site_id).all()
    posters = User.query.all()
    main_picture = Picture.query.filter_by(siteid=site_id).first()
    if (main_picture):
        main_picture_path = main_picture.path
    else:
        main_picture_path = ""
    form = PostCommentForm()
    return render_template("site/site_info.html",  site=site, genre=genre, creator=creator, comments=comments, main_picture_path=main_picture_path, form=form)

# サイト情報編集
@main.route("/edit_site/<int:site_id>", methods=["GET", "POST"])
@login_required
@auth.login_required
def edit_site(site_id):
    form = CreateSiteForm()
    site = Sitedata.query.filter_by(siteid=site_id).first()
    genre = Genre.query.filter_by(genid=site.category).first()
    current = int(current_user.get_id())
    main_picture = Picture.query.filter_by(siteid=site_id).first()
    if (main_picture):
        main_picture_path = main_picture.path
    else:
        main_picture_path = ""

    if form.validate_on_submit():
        site.sitename = form.sitename.data
        site.content = form.content.data
        site.coordinates = str(form.latitude.data) + "," + str(form.longitude.data)

        if form.image.data:
            image = form.image.data
            extension = os.path.splitext(image.filename)[1]
            filename = f"site{site.siteid}{extension}"
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            os.makedirs(os.path.dirname(image_path), exist_ok=True)
            image.save(image_path)
            main_picture.path = filename
        db.session.commit()
        return redirect(url_for("main.site_info", site_id=site_id))

flask_app/templates/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}{% endblock %}</title>
        {% block static %}{% endblock %}
    </head>
    {% block content %}{% endblock %}
</html>

flask_app/templates/edit_user.html
{% extends "base.html" %}
{% block title %}ユーザー編集{% endblock %}
{% block static %}
<link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/login.css') }}"
/>
{% endblock %}
{% block content %}
<body>
{% include "header.html" %}
<div class="login">
    <div class="login-triangle"></div>
    <h2 class = "login-header-hukidashi">ユーザー編集</h2>
    <form
        action="{{ url_for('main.edit_user', user_id=user.id) }}"
        method="POST"
        novalidate="novalidate"
        class = "login-container"
    >
        {{ form.csrf_token }}
        <p>
            {{ form.username.label }} {{ form.username(placeholder="ユーザー名", value=user.username) }}
        </p>
        {% for error in form.username.errors %}
        <span style="color:red;">{{ error }}</span>
        {% endfor %}
        <p>
            {{ form.email.label }} {{ form.email(placeholder="メールアドレス", value=user.email) }}
        </p>
        {% for error in form.email.errors %}
        <span style="color:red;">{{ error }}</span>
        {% endfor %}
        <p>
            {{ form.password.label }} {{ form.password(placeholder="パスワード", value=user.password) }}
        </p>
        {% for error in form.password.errors %}
        <span style="color:red;">{{ error }}</span>
        {% endfor %}
        <p><input type="submit" value="更新" /></p>
        
    </form>
    <br>
    <form
        action="{{ url_for('main.delete_user', user_id=user.id) }}"
        method="post"
        >
        {{ form.csrf_token }}
        <p><input type="submit" class="submit-erase" value="削除" /></p>
    </form>
    <br>
    <p><a href="{{url_for('main.users')}}" class = "togray">キャンセル</a></p>
</div>
</body>
{% endblock %}

flask_app/templates/fixheader.html
{% extends "base.html" %}
{% block title %}ヘッダー{% endblock %}
{% block static %}
<link
    rel="stylesheet" href="{{url_for('static',filename='css/header.css')}}"
/>
{% endblock %}
{% block content %}
<body>
    <header>
        
        <h1 class="title">つくマップ</h1>
        </header>
</body>
{% endblock %}

flask_app/templates/header.html
{% extends "base.html" %}
{% block title %}ヘッダー{% endblock %}
{% block static %}
<link
    rel="stylesheet" href="{{url_for('static',filename='css/header.css')}}"
/>
{% endblock %}
{% block content %}
<body>
    <header>
        <h1 class="title">
            <a href="{{url_for('main.maps')}}" class="header">つくマップ</a>
        </h1>
    </header>
</body>
{% endblock %}

flask_app/templates/login.html
{% extends "base.html" %}
{% block title %}ログイン{% endblock %}
{% block static %}
<link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/login.css') }}"
/>
{% endblock %}
{% block content %}
<body>
{% include "fixheader.html" %}
<div class="login">
    <div class="login-triangle"></div>
    <h2 class = "login-header-hukidashi">ログイン</h2>
    <form
        action="{{url_for('main.login')}}"
        method="POST"
        novalidate="novalidate"
        class = "login-container"
    >
        {% for message in get_flashed_messages() %}
        <p style="color: red;">{{ message }}</p>
        {% endfor %}
        {{ form.csrf_token }}
        <p>{{ form.email.label }} {{ form.email(placeholder="メールアドレス") }}</p>
        {% for error in form.email.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <p>{{ form.password.label }} {{ form.password(placeholder="パスワード") }}</p>
        {% for error in form.password.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <p>{{ form.submit() }}</p>    
    </form>
    <p><a href="{{url_for('main.signup')}}" class = "change">新規登録はこちら</a></p>
</div>
</body>
{% endblock %}

flask_app/templates/maps.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block static %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/maps.css') }}"/>
<script type="module" src="{{ url_for('static', filename='js/map_utils.js') }}"></script>
<!-- Leaflet用 -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="crossorigin=""/>
<!-- Google Fonts Icons -->
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<!-- Leaflet -->
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="crossorigin=""></script>
{% endblock %}


{% block content %}
<body>
    {% include "header.html" %}
    <span class="open-btn material-symbols-outlined">menu</span>
    <div class="sidebar">
        <div class="heading-box">
            <!-- ユーザ情報
            <a class="heading-user" href="{{ url_for('main.users') }}">ユーザ情報</a>
            ユーザ情報-->
            <div class="close-btn">
                <span class="material-symbols-outlined">close</span>
            </div>
            <a class="heading" href="{{ url_for('main.genres') }}">ジャンル一覧</a>
        </div>
        <ul class="genre-list">
            <div class="list show">
                <p>表示中</p>
                {% for genre in genres %}
                <li id="genre{{ genre.genid }}" class="genre">{{ genre.genname }}</li>
                {% endfor %}
            </div>
            <div class="list hide">
                <p>非表示</p>   
            </div>
        </ul>
    </div>
    <div id="map"></div>
    <script type="module" src="{{ url_for('static', filename='js/maps.js') }}"></script>
</body>
{% endblock %}

flask_app/templates/signup.html
{% extends "base.html" %}
{% block title %}ユーザー新規登録{% endblock %}
{% block static %}
<link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/login.css') }}"
/>

{% endblock %}
{% block content %}
<body>
{% include "fixheader.html" %}
<div class="login">
    <div class="login-triangle"></div>
    <h2 class = "login-header-hukidashi">ユーザー新規登録</h2>
    <form
        action="{{url_for('main.signup', next=request.args.get('next'))}}"
        method="POST"
        novalidate="novalidate"
        class = "login-container"
    >
        {% for message in get_flashed_messages() %}
        <p style="color: red;">{{ message }}</p>
        {% endfor %}
            {{ form.csrf_token }}
            <p>
                {{ form.username.label }}
                {{ form.username(size=30, placeholder="ユーザー名") }}
            </p>
            {% for error in form.username.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
            <p>{{ form.email.label }} {{ form.email(placeholder="メールアドレス") }}</p>
            {% for error in form.email.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
            <p>{{ form.password.label }} {{ form.password(placeholder="パスワード") }}</p>
            {% for error in form.password.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
            <p>{{ form.submit() }}</p>
    </form>
    <p><a href="{{url_for('main.login')}}" class = "change">ログインはこちら</a></p>
</div>
</body>
{% endblock %}

flask_app/templates/users.html
{% extends "base.html" %}
{% block title %}ユーザーの一覧{% endblock %}
{% block content %}
<link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/login.css') }}"
/>

<body>
{% include "header.html" %}
<div class="login">
    <h2 class ="login-header">ユーザーの一覧</h2>
    <br>

    <a href="{{ url_for('main.signup') }} " class = "change">ユーザー新規作成</a>
    <br>
    <table cellspacing="15">
        <tr>
            <th>ユーザーID</th>
            <th>ユーザー名</th>
            <th>メールアドレス</th>
        </tr>
        {% for user in users %}
        <tr>
            <th>
            <a href="{{ url_for('main.edit_user', user_id=user.id) }}" class = "tonext">{{ user.id }}</a>
            </th>
            <th>{{ user.username }}</th>
            <th>{{ user.email }}</th>
        </tr>
        {% endfor %}
    </table>
</div>
</body>
{% endblock %}