flask_app/views.py
import os
from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify, current_app
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.utils import secure_filename
from flask_app import db, auth
from flask_app.forms import SignUpForm, LoginForm, CreateGenreForm, CreateSiteForm, PostCommentForm
from flask_app.models import User, Genre, Sitedata, Comment, Picture

main = Blueprint(
    "main",
    __name__,
    template_folder="templates",
    static_folder="static",
)

# メインの地図のページ
@main.route("/")
@login_required
@auth.login_required
def maps():
    genres = Genre.query.all()
    Users = User.query.all()
    return render_template("maps.html", genres=genres)

@main.route("/data")
@auth.login_required
def get_data():
    sites = Sitedata.query.all()
    data = []
    for site in sites:
        category_id = site.category
        data.append({
            "siteid": site.siteid,
            "sitename": site.sitename,
            "coordinates": site.coordinates,
            "categoryid": category_id,
            "categoryname": Genre.query.filter_by(genid=category_id).one().genname,
        })
    json_data = jsonify(data)
    return json_data

@main.route("/data/<int:site_id>")
@auth.login_required
def get_sitedata(site_id):
    site = Sitedata.query.filter_by(siteid=site_id).first()
    category_id = site.category
    data = [{
        "siteid": site.siteid,
        "sitename": site.sitename,
        "coordinates": site.coordinates,
        "categoryid": category_id,
        "categoryname": Genre.query.filter_by(genid=category_id).one().genname,
    }]
    json_data = jsonify(data)
    return json_data

@main.route("/genres_data")
@auth.login_required
def get_genre_data():
    genres = Genre.query.all()
    data = []
    for genre in genres:
        data.append({
            "genid": genre.genid,
            "genname": genre.genname,
        })
    json_data = jsonify(data)
    return json_data

# サインアップページ
@main.route("/signup", methods=["GET", "POST"])
@auth.login_required
def signup():
    form = SignUpForm()
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )

        if user.is_duplicate_email():
            flash("指定のメールアドレスは登録済みです")
            return redirect(url_for("main.signup"))

        db.session.add(user)
        db.session.commit()

        login_user(user)

        next_ = request.args.get("next")
        if next_ is None or not next_.startswith("/"):
            next_ = url_for("main.maps")
        return redirect(next_)

    return render_template("signup.html", form=form)

# ログインページ
@main.route("/login", methods=["GET", "POST"])
@auth.login_required
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.query(User).filter_by(email=form.email.data).first()

        if user is not None and user.verify_password(form.password.data):
            login_user(user)
            return redirect(url_for("main.maps"))
        
        flash("メールアドレスかパスワードが不正です")
    return render_template("login.html", form=form)

# ログアウトする時に用いる
@main.route("/logout")
@auth.login_required
def logout():
    logout_user()
    return redirect(url_for("main.login"))

# ユーザ一覧 開発用
@main.route("/users")
@login_required
@auth.login_required
def users():
    users = db.session.query(User).all()
    return render_template("users.html", users=users)

# ユーザ情報編集
@main.route("/users/<int:user_id>", methods=["GET", "POST"])
@login_required
@auth.login_required
def edit_user(user_id):
    form = SignUpForm()
    user = User.query.filter_by(id=user_id).first()
    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.commit()
        return redirect(url_for("main.users"))
    return render_template("edit_user.html", user=user, form=form)

# ユーザ削除
@main.route("/users/<int:user_id>/delete", methods=["POST"])
@login_required
@auth.login_required
def delete_user(user_id):
    user = db.session.query(User).filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("main.users"))

# ジャンル一覧 開発用？
@main.route("/genres")
@login_required
@auth.login_required
def genres():
    genres = db.session.query(Genre).all()
    return render_template("genre/genres.html", genres=genres)

# ジャンル作成ページ
@main.route("/create_genre", methods=["GET", "POST"])
@login_required
@auth.login_required
def create_genre():
    form = CreateGenreForm()
    if form.validate_on_submit():
        genre = Genre(
            genname=form.genname.data,
            caption=form.caption.data,
            pins=0,
            creator=current_user.get_id()
        )
        db.session.add(genre)
        db.session.commit()

        return redirect(url_for("main.genres"))

    return render_template("genre/create_genre.html", form=form)

# ジャンル情報
@main.route("/genre/<int:genre_id>", methods=["GET"])
@login_required
@auth.login_required
def genre_info(genre_id):
    genre = Genre.query.filter_by(genid=genre_id).first()
    sites = Sitedata.query.filter_by(category=genre_id).all()
    creator = User.query.filter_by(id=genre.creator).first()
    return render_template("genre/genre_info.html", genre=genre, sites=sites, creator=creator)

# ジャンル情報（開発用）
@main.route("/genre/dev", methods=["GET"])
@auth.login_required
def dev_genre_info():
    return render_template("genre/dev_genre_info.html")

# ジャンル情報編集
@main.route("/edit_genre/<int:genre_id>", methods=["GET", "POST"])
@login_required
@auth.login_required
def edit_genre(genre_id):
    form = CreateGenreForm()
    genre = Genre.query.filter_by(genid=genre_id).first()
    current = int(current_user.get_id())
    if form.validate_on_submit():
        genre.genname = form.genname.data
        db.session.commit()
        return redirect(url_for("main.genres"))
    return render_template("genre/edit_genre.html", genre=genre, form=form, current=current)

# ジャンル削除
@main.route("/genre/<int:genre_id>/delete", methods=["POST"])
@login_required
@auth.login_required
def delete_genre(genre_id):
    genre = db.session.query(Genre).filter_by(genid=genre_id).first()
    sites = db.session.query(Sitedata).filter_by(category=genre_id).all()
    db.session.delete(genre)
    for site in sites:
        db.session.delete(site)
    db.session.commit()
    return redirect(url_for("main.genres"))

# サイト作成ページ
@main.route("/create_site/<int:genre_id>", methods=["GET", "POST"])
@login_required
@auth.login_required
def create_site(genre_id):
    genre = db.session.query(Genre).filter_by(genid=genre_id).first()
    form = CreateSiteForm()
    if form.validate_on_submit():

        site = Sitedata(
            sitename=form.sitename.data,
            category=genre_id,
            content=form.content.data,
            coordinates=str(form.latitude.data) + "," + str(form.longitude.data),
            creator=current_user.get_id()
        )
        db.session.add(site)
        db.session.flush()

        if form.image.data:
            image = form.image.data
            extension = os.path.splitext(image.filename)[1]
            filename = f"site{site.siteid}{extension}"
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            os.makedirs(os.path.dirname(image_path), exist_ok=True)
            image.save(image_path)
            picture = Picture(
                poster = current_user.id,
                siteid = site.siteid,
                path = filename,
            )
            db.session.add(picture)

        genre.pins += 1
        db.session.commit()

        return redirect(url_for("main.genre_info", genre_id=genre.genid))

    return render_template("site/create_site.html", genre=genre, form=form)

# サイト情報
@main.route("/site/<int:site_id>", methods=["GET"])
@login_required
@auth.login_required
def site_info(site_id):
    site = Sitedata.query.filter_by(siteid=site_id).first()
    genre = Genre.query.filter_by(genid=site.category).first()
    creator = User.query.filter_by(id=genre.creator).first()
    comments = Comment.query.filter_by(siteid=site_id).all()
    posters = User.query.all()
    main_picture = Picture.query.filter_by(siteid=site_id).first()
    if (main_picture):
        main_picture_path = main_picture.path
    else:
        main_picture_path = ""
    form = PostCommentForm()
    return render_template("site/site_info.html",  site=site, genre=genre, creator=creator, comments=comments, main_picture_path=main_picture_path, form=form)

# サイト情報編集
@main.route("/edit_site/<int:site_id>", methods=["GET", "POST"])
@login_required
@auth.login_required
def edit_site(site_id):
    form = CreateSiteForm()
    site = Sitedata.query.filter_by(siteid=site_id).first()
    genre = Genre.query.filter_by(genid=site.category).first()
    current = int(current_user.get_id())
    main_picture = Picture.query.filter_by(siteid=site_id).first()
    if (main_picture):
        main_picture_path = main_picture.path
    else:
        main_picture_path = ""

    if form.validate_on_submit():
        site.sitename = form.sitename.data
        site.content = form.content.data
        site.coordinates = str(form.latitude.data) + "," + str(form.longitude.data)

        if form.image.data:
            image = form.image.data
            extension = os.path.splitext(image.filename)[1]
            filename = f"site{site.siteid}{extension}"
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            os.makedirs(os.path.dirname(image_path), exist_ok=True)
            image.save(image_path)
            main_picture.path = filename
        db.session.commit()
        return redirect(url_for("main.site_info", site_id=site_id))

flask_app/templates/site/create_site.html
{% extends "base.html" %}
{% block title %}サイト新規登録{% endblock %}
{% block static %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/create_site.css') }}"/>
<script type="module" src="{{ url_for('static', filename='js/map_utils.js') }}"></script>
<!-- Leaflet用 -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="crossorigin=""/>
<!-- Leaflet -->
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="crossorigin=""></script>
<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
{% endblock %}

{% block content %}
<body>
    {% include "header.html" %}
    <div class = "site">
        <br>
        <h2 class = "site-header">サイト新規作成 （{{ genre.genname }}）</h2>

        <form
            action="{{url_for('main.create_site', genre_id=genre.genid)}}"
            method="POST"
            novalidate="novalidate"
            enctype="multipart/form-data"
        >
    
            {{ form.csrf_token }}
            <p>
                {{ form.sitename.label }}
                {{ form.sitename(size=30, placeholder="サイト名") }}
            </p>
            <p>
                {{ form.content.label }}
                {{ form.content(size=30, placeholder="場所の詳細やその他情報") }}
            </p>
            <p>
                {{ form.latitude.label }}{{ form.latitude(size=30, placeholder="地点をクリックで入力できます") }}
                {{ form.longitude.label }}{{ form.longitude(size=30, placeholder="地点をクリックで入力できます") }}
            </p>
            <div id="map"></div>
            <p>
                {{ form.image.label }}
                {{ form.image(id="upload-image") }}
            </p>
            <img id="preview" src="" />
            <p>
                {{ form.submit() }}
                <br>
                <a class = 'togray' href="{{ url_for('main.genre_info', genre_id=genre.genid) }}">キャンセル</a>
            </p>
        </form>
        <script>var genId = "{{ genre.genid }}"</script>
        <script type="module" src="{{ url_for('static', filename='js/create_site.js') }}"></script>
    </div>
</body>
{% endblock %}

flask_app/templates/site/edit_site.html
{% extends "base.html" %}
{% block title %}edit - {{ site.sitename }}{% endblock %}
{% block content %}
{% block static %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/create_site.css') }}"/>
<script type="module" src="{{ url_for('static', filename='js/map_utils.js') }}"></script>
<!-- Leaflet用 -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="crossorigin=""/>
<!-- Leaflet -->
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="crossorigin=""></script>
<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
{% endblock %}
<body>
    {% include "header.html" %}
    <div class = "site">
        <br>
        <h2 class = "site-header">サイト情報編集</h2>
        <form
            action="{{ url_for('main.edit_site', site_id=site.siteid) }}"
            method="POST"
            novalidate="novalidate"
            enctype="multipart/form-data"
        >
        {{ form.csrf_token }}
            <p>
                {{ form.sitename.label }} {{ form.sitename(placeholder="サイト名", value=site.sitename,size=30) }}
            </p>
            {% for error in form.sitename.errors %}
            <span style="color:red;">{{ error }}</span>
            {% endfor %}
            <p>
                {{ form.content.label }} {{ form.content(value=site.content) }}
            </p>
            {% for error in form.content.errors %}
            <span style="color:red;">{{ error }}</span>
            {% endfor %}
            <p>
                {{ form.latitude.label }}{{ form.latitude(size =30, placeholder="地点をクリックで更新できます") }}
                {{ form.longitude.label }}{{ form.longitude(size =30, placeholder="地点をクリックで更新できます") }}
            </p>
            {% for error in form.content.errors %}
            <span style="color:red;">{{ error }}</span>
            {% endfor %}
            <div id="map"></div>
            <p>
                {{ form.image.label }}
                {{ form.image(id="upload-image") }}
            </p>
            {% if main_picture_path %} 
                <img id="main-image" src="{{ url_for('static', filename='images/uploaded_images/' + main_picture_path) }}" />
            {% endif %}
            <p>
                <input type="submit" value="更新" />
                <br>
                <a class = "togray" href="{{ url_for('main.site_info', site_id=site.siteid) }}">キャンセル</a>
            </p>
        </form>
        {% if current == site.creator %}
            <p>
                <form 
                    action="{{ url_for('main.delete_site', site_id=site.siteid) }}"
                    method="post"
                >
                {{ form.csrf_token }}
                <p><input type="submit" class = "submit-erase" value="削除"></p>
                </form>
            </p>
        {% endif %}

        <script>
            var site_id = "{{ site.siteid }}";
        </script>
        <script type="module" src="{{ url_for('static', filename='js/edit_site.js') }}"></script>
    </div>
</body>
{% endblock %}

flask_app/templates/site/site_info.html
{% extends "base.html" %}
{% block title %}{{ site.sitename }}{% endblock %}
{% block static %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/create_site.css') }}"/>
<script type="module" src="{{ url_for('static', filename='js/map_utils.js') }}"></script>
<!-- Leaflet用 -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="crossorigin=""/>
<!-- Leaflet -->
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="crossorigin=""></script>
<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
{% endblock %}


{% block content %}
<body>
    {% include "header.html" %}
    <br>
    <div class = "site">
        <h2 class = "site-header">{{ site.sitename }}</h2>
        <p>座標: {{ site.coordinates }}</p>
        <p><a href="https://www.google.co.jp/maps/place/{{ site.coordinates }}" >GoogleMapsへ</a></p>
        <p><a class = "toedit" href="{{ url_for('main.edit_site', site_id=site.siteid) }}">編集</a></p>
        <!--<p>座標: {{ site.coordinates }}</p>-->
        <div id="map"></div>
        <p>{{ site.content }}</p>
        {% if main_picture_path %} 
            <img id="main-image" src="{{ url_for('static', filename='images/uploaded_images/' + main_picture_path) }}" />
        {% endif %}
        <ul>
        <!-- {% for picture in pictures %} -->
            <li><img src="" /></li> <!-- 後で実装 -->
        <!-- {% endfor %} -->
        </ul>
        <h3 class = "site-h3">コメント</h3>
        <form
            action="{{url_for('main.post_comment', site_id=site.siteid)}}"
            method="POST"
            novalidate="novalidate"
        >
            {{ form.csrf_token }}
            <p>
                <h4 class = "site-h4">{{ form.comment.label }}</h4>
                {{ form.comment(size=60) }}
                <br>
                {{ form.submit() }}
            </p>
        </form>
        <h4 class = "site-h4">コメント</h4>
        {% if comments %}
        <table>
            {% for comment in comments %}
                <tr>
                    <th>{{ comment.poster }} ： {{ comment.content }}</tr>
                </tr>
            {% endfor %}
        </table>
        {% else %}
            <p>コメントはまだありません。</p>
        {% endif%}

        <script>
            var site_id = "{{ site.siteid }}";
        </script>
        <script type="module" src="{{ url_for('static', filename='js/site_info.js') }}"></script>
        <br>
        <a href="{{ url_for('main.genre_info', genre_id=genre.genid) }}" class = "togray">ジャンル詳細へ</a>
    </div>
</body>
{% endblock %}