flask_app/views.py
import os
from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify, current_app
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.utils import secure_filename
from flask_app import db, auth
from flask_app.forms import SignUpForm, LoginForm, CreateGenreForm, CreateSiteForm, PostCommentForm
from flask_app.models import User, Genre, Sitedata, Comment, Picture

main = Blueprint(
    "main",
    __name__,
    template_folder="templates",
    static_folder="static",
)

# メインの地図のページ
@main.route("/")
@login_required
@auth.login_required
def maps():
    genres = Genre.query.all()
    Users = User.query.all()
    return render_template("maps.html", genres=genres)

@main.route("/data")
@auth.login_required
def get_data():
    sites = Sitedata.query.all()
    data = []
    for site in sites:
        category_id = site.category
        data.append({
            "siteid": site.siteid,
            "sitename": site.sitename,
            "coordinates": site.coordinates,
            "categoryid": category_id,
            "categoryname": Genre.query.filter_by(genid=category_id).one().genname,
        })
    json_data = jsonify(data)
    return json_data

@main.route("/data/<int:site_id>")
@auth.login_required
def get_sitedata(site_id):
    site = Sitedata.query.filter_by(siteid=site_id).first()
    category_id = site.category
    data = [{
        "siteid": site.siteid,
        "sitename": site.sitename,
        "coordinates": site.coordinates,
        "categoryid": category_id,
        "categoryname": Genre.query.filter_by(genid=category_id).one().genname,
    }]
    json_data = jsonify(data)
    return json_data

@main.route("/genres_data")
@auth.login_required
def get_genre_data():
    genres = Genre.query.all()
    data = []
    for genre in genres:
        data.append({
            "genid": genre.genid,
            "genname": genre.genname,
        })
    json_data = jsonify(data)
    return json_data

# サインアップページ
@main.route("/signup", methods=["GET", "POST"])
@auth.login_required
def signup():
    form = SignUpForm()
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )

        if user.is_duplicate_email():
            flash("指定のメールアドレスは登録済みです")
            return redirect(url_for("main.signup"))

        db.session.add(user)
        db.session.commit()

        login_user(user)

        next_ = request.args.get("next")
        if next_ is None or not next_.startswith("/"):
            next_ = url_for("main.maps")
        return redirect(next_)

    return render_template("signup.html", form=form)

# ログインページ
@main.route("/login", methods=["GET", "POST"])
@auth.login_required
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.query(User).filter_by(email=form.email.data).first()

        if user is not None and user.verify_password(form.password.data):
            login_user(user)
            return redirect(url_for("main.maps"))
        
        flash("メールアドレスかパスワードが不正です")
    return render_template("login.html", form=form)

# ログアウトする時に用いる
@main.route("/logout")
@auth.login_required
def logout():
    logout_user()
    return redirect(url_for("main.login"))

# ユーザ一覧 開発用
@main.route("/users")
@login_required
@auth.login_required
def users():
    users = db.session.query(User).all()
    return render_template("users.html", users=users)

# ユーザ情報編集
@main.route("/users/<int:user_id>", methods=["GET", "POST"])
@login_required
@auth.login_required
def edit_user(user_id):
    form = SignUpForm()
    user = User.query.filter_by(id=user_id).first()
    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.commit()
        return redirect(url_for("main.users"))
    return render_template("edit_user.html", user=user, form=form)

# ユーザ削除
@main.route("/users/<int:user_id>/delete", methods=["POST"])
@login_required
@auth.login_required
def delete_user(user_id):
    user = db.session.query(User).filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("main.users"))

# ジャンル一覧 開発用？
@main.route("/genres")
@login_required
@auth.login_required
def genres():
    genres = db.session.query(Genre).all()
    return render_template("genre/genres.html", genres=genres)

# ジャンル作成ページ
@main.route("/create_genre", methods=["GET", "POST"])
@login_required
@auth.login_required
def create_genre():
    form = CreateGenreForm()
    if form.validate_on_submit():
        genre = Genre(
            genname=form.genname.data,
            caption=form.caption.data,
            pins=0,
            creator=current_user.get_id()
        )
        db.session.add(genre)
        db.session.commit()

        return redirect(url_for("main.genres"))

    return render_template("genre/create_genre.html", form=form)

# ジャンル情報
@main.route("/genre/<int:genre_id>", methods=["GET"])
@login_required
@auth.login_required
def genre_info(genre_id):
    genre = Genre.query.filter_by(genid=genre_id).first()
    sites = Sitedata.query.filter_by(category=genre_id).all()
    creator = User.query.filter_by(id=genre.creator).first()
    return render_template("genre/genre_info.html", genre=genre, sites=sites, creator=creator)

# ジャンル情報（開発用）
@main.route("/genre/dev", methods=["GET"])
@auth.login_required
def dev_genre_info():
    return render_template("genre/dev_genre_info.html")

# ジャンル情報編集
@main.route("/edit_genre/<int:genre_id>", methods=["GET", "POST"])
@login_required
@auth.login_required
def edit_genre(genre_id):
    form = CreateGenreForm()
    genre = Genre.query.filter_by(genid=genre_id).first()
    current = int(current_user.get_id())
    if form.validate_on_submit():
        genre.genname = form.genname.data
        db.session.commit()
        return redirect(url_for("main.genres"))
    return render_template("genre/edit_genre.html", genre=genre, form=form, current=current)

# ジャンル削除
@main.route("/genre/<int:genre_id>/delete", methods=["POST"])
@login_required
@auth.login_required
def delete_genre(genre_id):
    genre = db.session.query(Genre).filter_by(genid=genre_id).first()
    sites = db.session.query(Sitedata).filter_by(category=genre_id).all()
    db.session.delete(genre)
    for site in sites:
        db.session.delete(site)
    db.session.commit()
    return redirect(url_for("main.genres"))

# サイト作成ページ
@main.route("/create_site/<int:genre_id>", methods=["GET", "POST"])
@login_required
@auth.login_required
def create_site(genre_id):
    genre = db.session.query(Genre).filter_by(genid=genre_id).first()
    form = CreateSiteForm()
    if form.validate_on_submit():

        site = Sitedata(
            sitename=form.sitename.data,
            category=genre_id,
            content=form.content.data,
            coordinates=str(form.latitude.data) + "," + str(form.longitude.data),
            creator=current_user.get_id()
        )
        db.session.add(site)
        db.session.flush()

        if form.image.data:
            image = form.image.data
            extension = os.path.splitext(image.filename)[1]
            filename = f"site{site.siteid}{extension}"
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            os.makedirs(os.path.dirname(image_path), exist_ok=True)
            image.save(image_path)
            picture = Picture(
                poster = current_user.id,
                siteid = site.siteid,
                path = filename,
            )
            db.session.add(picture)

        genre.pins += 1
        db.session.commit()

        return redirect(url_for("main.genre_info", genre_id=genre.genid))

    return render_template("site/create_site.html", genre=genre, form=form)

# サイト情報
@main.route("/site/<int:site_id>", methods=["GET"])
@login_required
@auth.login_required
def site_info(site_id):
    site = Sitedata.query.filter_by(siteid=site_id).first()
    genre = Genre.query.filter_by(genid=site.category).first()
    creator = User.query.filter_by(id=genre.creator).first()
    comments = Comment.query.filter_by(siteid=site_id).all()
    posters = User.query.all()
    main_picture = Picture.query.filter_by(siteid=site_id).first()
    if (main_picture):
        main_picture_path = main_picture.path
    else:
        main_picture_path = ""
    form = PostCommentForm()
    return render_template("site/site_info.html",  site=site, genre=genre, creator=creator, comments=comments, main_picture_path=main_picture_path, form=form)

# サイト情報編集
@main.route("/edit_site/<int:site_id>", methods=["GET", "POST"])
@login_required
@auth.login_required
def edit_site(site_id):
    form = CreateSiteForm()
    site = Sitedata.query.filter_by(siteid=site_id).first()
    genre = Genre.query.filter_by(genid=site.category).first()
    current = int(current_user.get_id())
    main_picture = Picture.query.filter_by(siteid=site_id).first()
    if (main_picture):
        main_picture_path = main_picture.path
    else:
        main_picture_path = ""

    if form.validate_on_submit():
        site.sitename = form.sitename.data
        site.content = form.content.data
        site.coordinates = str(form.latitude.data) + "," + str(form.longitude.data)

        if form.image.data:
            image = form.image.data
            extension = os.path.splitext(image.filename)[1]
            filename = f"site{site.siteid}{extension}"
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            os.makedirs(os.path.dirname(image_path), exist_ok=True)
            image.save(image_path)
            main_picture.path = filename
        db.session.commit()
        return redirect(url_for("main.site_info", site_id=site_id))

flask_app/templates/genre/create_genre.html
{% extends "base.html" %}
{% block title %}ジャンル新規登録{% endblock %}
{% block static %}

<link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/genre.css') }}"
/>
{% endblock %}
{% block content %}
<body>
{% include "header.html" %}
<div class="genre">
    <h2 class = "genre-header">ジャンル新規作成</h2>
    <form
        action="{{url_for('main.create_genre', next=request.args.get('next'))}}"
        method="POST"
        novalidate="novalidate"
    >
        {{ form.csrf_token }}
        <p>
            {{ form.genname.label }}
            {{ form.genname(size=30, placeholder="ジャンル名") }}
        </p>
        {% for error in form.genname.errors %}
        <span style="color:red;">{{ error }}</span>
        {% endfor %}
        <p>
            {{ form.caption.label }}
            {{ form.caption(size=60, placeholder="ジャンルについての説明") }}
        </p>
        <br>
        <p>{{ form.submit() }}</p>
    </form>
    <br>
    <a href="{{url_for('main.genres')}}" class = "togray">一覧へ</a>
</div>
</body>
{% endblock %}

flask_app/templates/genre/dev_genre_info.html
{% extends "base.html" %}
{% block title %}駐輪場{% endblock %}

{% block content %}
{% include "header.html" %}
<h2>駐輪場</h2>
<a href="#">編集</a>
<p>筑波大学周辺で自転車を停められる場所をまとめました。</p>

<ul>
    <li>春日講堂近く <a href="https://www.google.co.jp/maps/place/36%C2%B005'13.3%22N+140%C2%B006'21.1%22E/@36.0870293,140.1032774,17z/data=!3m1!4b1!4m4!3m3!8m2!3d36.087025!4d140.105847?hl=ja&entry=ttu">Google マップへ</a></li>
    <li>CEGLOC前 <a href="https://www.google.co.jp/maps/place/36%C2%B006'16.1%22N+140%C2%B006'09.4%22E/@36.1044683,140.1000314,17z/data=!3m1!4b1!4m4!3m3!8m2!3d36.104464!4d140.102601?hl=ja&entry=ttu">Google マップへ</a></li>
    <li>大学会館前 <a href="https://www.google.co.jp/maps/place/36%C2%B006'19.5%22N+140%C2%B006'08.5%22E/@36.1054291,140.1017196,220m/data=!3m2!1e3!4b1!4m4!3m3!8m2!3d36.105428!4d140.102362?hl=ja&entry=ttu">Google マップへ</a></li>
</ul>
{% endblock %}

flask_app/templates/genre/edit_genre.html
{% extends "base.html" %}
{% block title %}edit - {{ genre.genname }}{% endblock %}

{% block static %}
<link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/genre.css') }}"
/>
{% endblock %}
{% block content %}
<body>
    {% include "header.html" %}
<div class="genre">
    <h2 class = "genre-header">ジャンル情報編集</h2>
    <form
        action="{{ url_for('main.edit_genre', genre_id=genre.genid) }}"
        method="POST"
        novalidate="novalidate"
    >
    {{ form.csrf_token }}
        <p>
            {{ form.genname.label }} {{ form.genname(placeholder="ジャンル名", value=genre.genname) }}
        </p>
        {% for error in form.genname.errors %}
        <span style="color:red;">{{ error }}</span>
        {% endfor %}
        <p>
            {{ form.caption.label }}
            {{ form.caption(placeholder="ジャンルについての説明",value=genre.caption) }}
        </p>
        <br>
        <p><input type="submit" value="更新" /></p>
    </form>
    {% if current == genre.creator %}
    <form 
        action="{{ url_for('main.delete_genre', genre_id=genre.genid) }}"
        method="post"
    >
        {{ form.csrf_token }}
        <br>
        <br>
        <p><input type="submit" class = "submit-erase" value="削除"></p>
        <br>
    </form>
    {% endif %}
    <a href="{{url_for('main.genres')}}" class = "togray">ジャンル一覧へ</a>
</div>
</body>
{% endblock %}

flask_app/templates/genre/genre_info.html
{% extends "base.html" %}
{% block title %}{{ genre.genname }}{% endblock %}
{% block static %}
<link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/genre.css') }}"
/>
{% endblock %}
{% block content %}
<body>
    {% include "header.html" %}
<div class="genre">
    <h2 class = "genre-header">{{ genre.genname }}</h2>
    <p>説明：{{ genre.caption }}</p>
    <p style = "color:#696969">作成者：{{ creator.username }}</p>
    <p><a href="{{url_for('main.edit_genre', genre_id=genre.genid)}}" class = "togreen">ジャンル情報編集</a></p>
    <hr>
    <br>
    <p><a href="{{url_for('main.create_site', genre_id=genre.genid)}}" class = "tonew">地点の追加</a></p>
    <br>登録済みの地点<br>
    <ul>
    {% for site in sites %}
        <li><a href="{{ url_for('main.site_info', site_id=site.siteid) }}" class = "tonext">{{ site.sitename }}</a></li>
    {% endfor %}
    </ul>
    <br>
    <a href="{{url_for('main.genres')}}" class = "togray fixed-bottom">ジャンル一覧へ</a>
</div>
</body>
{% endblock %}

flask_app/templates/genre/genres.html
{% extends "base.html" %}
{% block title %}ジャンル一覧{% endblock %}
{% block static %}
<link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/genre.css') }}"
/>
{% endblock %}
{% block content %}
<body>
{% include "header.html" %}
<div class="genre">
    <h2 class = "genre-header" >ジャンル一覧</h2>
    <br>
    <a href="{{ url_for('main.create_genre') }}" class = "tonew">ジャンル新規作成🖊</a>
    <br>
    <br>
    <table>
        <tr>
            <th>ジャンル名</th>
            <th>説明</th>
            <th>登録された地点</th>
        </tr>

        {% for genre in genres %}
        <tr>
            <th><a href="{{url_for('main.genre_info', genre_id=genre.genid)}}" class = "tonext">{{ genre.genname }}</a></th>
            <th>{{ genre.caption }}</th>
            <th>{{ genre.pins }}</th>
        </tr>
        {% endfor %}
    </table>
    <br>
    <a href="{{url_for('main.maps')}}" class = "togray">地図へ戻る</a>
</div>
</body>
{% endblock %}